from dataclasses import dataclass


class Quake3:
    """
    Quake 3 protocol 68.
    """

    entity_types = [
        'ET_GENERAL',
        'ET_PLAYER',
        'ET_ITEM',
        'ET_MISSILE',
        'ET_MOVER',
        'ET_BEAM',
        'ET_PORTAL',
        'ET_SPEAKER',
        'ET_PUSH_TRIGGER',
        'ET_TELEPORT_TRIGGER',
        'ET_INVISIBLE',
        'ET_GRAPPLE',
        'ET_TEAM',
        'ET_EVENTS',
    ]

    events = [
        'EV_NONE',
        'EV_FOOTSTEP',
        'EV_FOOTSTEP_METAL',
        'EV_FOOTSPLASH',
        'EV_FOOTWADE',
        'EV_SWIM',
        'EV_STEP_4',
        'EV_STEP_8',
        'EV_STEP_12',
        'EV_STEP_16',
        'EV_FALL_SHORT',
        'EV_FALL_MEDIUM',
        'EV_FALL_FAR',
        'EV_JUMP_PAD',
        'EV_JUMP',
        'EV_WATER_TOUCH',
        'EV_WATER_LEAVE',
        'EV_WATER_UNDER',
        'EV_WATER_CLEAR',
        'EV_ITEM_PICKUP',
        'EV_GLOBAL_ITEM_PICKUP',
        'EV_NOAMMO',
        'EV_CHANGE_WEAPON',
        'EV_FIRE_WEAPON',
        'EV_USE_ITEM0',
        'EV_USE_ITEM1',
        'EV_USE_ITEM2',
        'EV_USE_ITEM3',
        'EV_USE_ITEM4',
        'EV_USE_ITEM5',
        'EV_USE_ITEM6',
        'EV_USE_ITEM7',
        'EV_USE_ITEM8',
        'EV_USE_ITEM9',
        'EV_USE_ITEM10',
        'EV_USE_ITEM11',
        'EV_USE_ITEM12',
        'EV_USE_ITEM13',
        'EV_USE_ITEM14',
        'EV_USE_ITEM15',
        'EV_ITEM_RESPAWN',
        'EV_ITEM_POP',
        'EV_PLAYER_TELEPORT_IN',
        'EV_PLAYER_TELEPORT_OUT',
        'EV_GRENADE_BOUNCE',
        'EV_GENERAL_SOUND',
        'EV_GLOBAL_SOUND',
        'EV_GLOBAL_TEAM_SOUND',
        'EV_BULLET_HIT_FLESH',
        'EV_BULLET_HIT_WALL',
        'EV_MISSILE_HIT',
        'EV_MISSILE_MISS',
        'EV_MISSILE_MISS_METAL',
        'EV_RAILTRAIL',
        'EV_SHOTGUN',
        'EV_BULLET',
        'EV_PAIN',
        'EV_DEATH1',
        'EV_DEATH2',
        'EV_DEATH3',
        'EV_OBITUARY',
        'EV_POWERUP_QUAD',
        'EV_POWERUP_BATTLESUIT',
        'EV_POWERUP_REGEN',
        'EV_GIB_PLAYER',
        'EV_SCOREPLUM',
        'EV_PROXIMITY_MINE_STICK',
        'EV_PROXIMITY_MINE_TRIGGER',
        'EV_KAMIKAZE',
        'EV_OBELISKEXPLODE',
        'EV_OBELISKPAIN',
        'EV_INVUL_IMPACT',
        'EV_JUICED',
        'EV_LIGHTNINGBOLT',
        'EV_DEBUG_LINE',
        'EV_STOPLOOPINGSOUND',
        'EV_TAUNT',
        'EV_TAUNT_YES',
        'EV_TAUNT_NO',
        'EV_TAUNT_FOLLOWME',
        'EV_TAUNT_GETFLAG',
        'EV_TAUNT_GUARDBASE',
        'EV_TAUNT_PATROL',
    ]

    @dataclass
    class State:
        name: str
        bit_size: int = 0

    entity_states = [
        State('pos.trTime', 32),
        State('pos.trBase[0]'),
        State('pos.trBase[1]'),
        State('pos.trDelta[0]'),
        State('pos.trDelta[1]'),
        State('pos.trBase[2]'),
        State('apos.trBase[1]'),
        State('pos.trDelta[2]'),
        State('apos.trBase[0]'),
        State('event', 10),
        State('angles2[1]'),
        State('eType', 8),
        State('torsoAnim', 8),
        State('eventParm', 8),
        State('legsAnim', 8),
        State('groundEntityNum', 10),
        State('pos.trType', 8),
        State('eFlags', 19),
        State('otherEntityNum', 10),
        State('weapon', 8),
        State('clientNum', 8),
        State('angles[1]'),
        State('pos.trDuration', 32),
        State('apos.trType', 8),
        State('origin[0]'),
        State('origin[1]'),
        State('origin[2]'),
        State('solid', 24),
        State('powerups', 16),
        State('modelindex', 8),
        State('otherEntityNum2', 10),
        State('loopSound', 8),
        State('generic1', 8),
        State('origin2[2]'),
        State('origin2[0]'),
        State('origin2[1]'),
        State('modelindex2', 8),
        State('angles[0]'),
        State('time', 32),
        State('apos.trTime', 32),
        State('apos.trDuration', 32),
        State('apos.trBase[2]'),
        State('apos.trDelta[0]'),
        State('apos.trDelta[1]'),
        State('apos.trDelta[2]'),
        State('time2', 32),
        State('angles[2]'),
        State('angles2[0]'),
        State('angles2[2]'),
        State('constantLight', 32),
        State('frame', 16),
    ]

    player_states = [
        State('commandTime', 32),
        State('origin[0]'),
        State('origin[1]'),
        State('bobCycle', 8),
        State('velocity[0]'),
        State('velocity[1]'),
        State('viewangles[1]'),
        State('viewangles[0]'),
        State('weaponTime', -16),
        State('origin[2]'),
        State('velocity[2]'),
        State('legsTimer', 8),
        State('pm_time', -16),
        State('eventSequence', 16),
        State('torsoAnim', 8),
        State('movementDir', 4),
        State('events[0]', 8),
        State('legsAnim', 8),
        State('events[1]', 8),
        State('pm_flags', 16),
        State('groundEntityNum', 10),
        State('weaponstate', 4),
        State('eFlags', 16),
        State('externalEvent', 10),
        State('gravity', 16),
        State('speed', 16),
        State('delta_angles[1]', 16),
        State('externalEventParm', 8),
        State('viewheight', -8),
        State('damageEvent', 8),
        State('damageYaw', 8),
        State('damagePitch', 8),
        State('damageCount', 8),
        State('generic1', 8),
        State('pm_type', 8),
        State('delta_angles[0]', 16),
        State('delta_angles[2]', 16),
        State('torsoTimer', 12),
        State('eventParms[0]', 8),
        State('eventParms[1]', 8),
        State('clientNum', 8),
        State('weapon', 5),
        State('viewangles[2]'),
        State('grapplePoint[0]'),
        State('grapplePoint[1]'),
        State('grapplePoint[2]'),
        State('jumppad_ent', 10),
        State('loopSound', 16),
    ]
